#!/bin/sh
# Script to configure X, start common apps, and start xmonad.
# Author: Vic Fryzel
# http://github.com/vicfryzel/xmonad-config

# Configure PATH so that we can access our scripts below
PATH=$PATH:~/.cabal/bin:~/.xmonad/bin

# Setup background
feh --bg-scale ~/Pictures/shinobi.jpg

# Start a window compositor. This ensures Google Chrome paints correctly.
compton --config ~/.xmonad/compton.conf &
xfce4-power-manager &
